version: '3.8'

services:
  pgdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  spring-boot-app:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - pgdb
volumes:
  postgres_data: